//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVMSApp.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class visa
    {
        public string userId { get; set; }
        public string country { get; set; }
        public string occupation { get; set; }
        public System.DateTime dateOfApplication { get; set; }
        public string visaId { get; set; }
        public System.DateTime dateOfIssue { get; set; }
        public System.DateTime dateOfExpiry { get; set; }
        public double cost { get; set; }
        public string passportId { get; set; }
        public string status { get; set; }
    
        public virtual user_registration2 user_registration2 { get; set; }
    }
}
