//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVMSApp.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visa_form
    {
        public string Occupation { get; set; }
        public string Country { get; set; }
        public double Amount { get; set; }
        public double Validity { get; set; }
    }
}
